In [1]:
import numpy as np


Logistic Regression

In [18]:
# Logistic Regresion
class LogisticRegression:
    # we define every theta into object perameeters self
    def __init__ (self,learning_rate=0.1,n_iter=1000):
        # perameters that we need
        self.bias= None
        self.weights= None
        self.lr=learning_rate
        self.n_iter=n_iter

    def _sigmoid(self,z):
        return(1/(1+np.exp(-z)))
        
    def fit(self,X ,y):
        m,n= X.shape  #sample of data ,numbers of features
        
        # STEP 1- initilize perameeters that we need
        self.bias=0
        self.weights=np.zeros(n) 

        # GREDIENT DESCENT
        for i in range (self.n_iter):  
             
            # STEP2-  calclate y predict
            z=self.bias+ np.dot(X,self.weights)
            y_pred=self._sigmoid(z)
            
            # STEP3 - calcualte gredients
            db=(1/m)*(y_pred - y)
            dw=(1/m)*np.dot(X.T,(y_pred- y))

            # STEP4- apply conversion theorum for perameters update
            self.bias -= self.lr*db
            self.weights -= self.lr*dw

    def get_probabilities(self,X):
            z=self.bias+ np.dot(X,self.weights)
            return self._sigmoid(z)
        
    def predict(self,X,threshold=0.5):   
        probability=self.get_probabilities(X)
        y_pred=probability >= threshold
        return y_pred.astype(int)
        


In [12]:
arr= np.array([0.67,0.56,0.75,0.23,0.1])
(arr >=0.5).astype(int)



array([1, 1, 1, 0, 0])

In [23]:
X=np.array([[1,2],[3,4],[5,6],[7,8]])
y=np.array([0,1,0,1])


model=LogisticRegression()
model.fit(X,y)

y_pred=model.predict(X)
print(y_pred)
print(model.get_probabilities(X))

[0 1 0 1]
[0.0363352  0.95988402 0.05094553 0.97386339]
